### ISSUE TITLE
Having a white space in the User/"name" folder leads to the editor not opening

### ISSUE THREAD

**Issue by blake-tisbury** [TheAshenWolf/WakaTimeForUE#22]
Having a whitespace in your user folder causes the editor to exit on startup with the error "Path 'C:/Users/{name}' could not be found". The path is there, it just seems like the plugin cuts the path off at the space so instead of it searching for "My name" it searches for "My" which returns an error. Is there any way to allow white spaces so users with one in their user folders can open the plugin? I tried looking through the source code but couldn't find a way to let it see past spaces.  (Creating this issue on behalf of one of my team members, other than that the plugin works great, thank you!)

**Comment by TheAshenWolf** [comment]
Good day,
I believe that wrapping all the `string(GUserProfile)` with `\"` should fix this issue. 

I am not sure if I still have Unreal Engine on my machine, as I was not developing within it a long time, but if I do, I will attempt to fix this issue today ;) 

Thank you!

**Comment by blake-tisbury** [comment]
Hey there, sorry I didn't see the other message, thanks a ton! I'll let him know.
